export type ManifestoBlock =
  | { type: 'h1'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'p'; text: string }
  | { type: 'quote'; text: string }
  | { type: 'strong'; text: string }
  | { type: 'rule' };

export const MANIFESTO_BLOCKS: ManifestoBlock[] = [
  { type: 'h1', text: 'The ManifestOS Manifesto' },
  { type: 'h2', text: 'Everyone sees problems. Everyone should be able to solve them.' },
  { type: 'p', text: 'For most of computing history, software had an invisible admission price.' },
  { type: 'p', text: 'A problem had to be important enough.' },
  { type: 'p', text: 'Important enough to enough people. Profitable enough to justify developers. Large enough to deserve a budget, a product team, months of engineering, and eventually a company willing to build it.' },
  { type: 'p', text: 'That made sense when software was expensive to create.' },
  { type: 'p', text: "But it also meant that millions of perfectly real problems simply weren't worth solving with software." },
  { type: 'p', text: 'The problem experienced by one family.' },
  { type: 'p', text: 'The strange workflow only a mechanic understands.' },
  { type: 'p', text: 'The classroom frustration affecting three students.' },
  { type: 'p', text: 'The routine a caregiver invented because nothing available quite fits.' },
  { type: 'p', text: 'The tiny inefficiency everyone at one small business has complained about for years.' },
  { type: 'p', text: "The idea somebody has said, a hundred times:" },
  { type: 'strong', text: '“I wish there were something that did this.”' },
  { type: 'p', text: 'We think that sentence is about to become much more powerful.' },
  { type: 'rule' },
  { type: 'h2', text: 'A problem should not need a market before it deserves a solution.' },
  { type: 'p', text: 'AI is changing the economics of creation.' },
  { type: 'p', text: 'Software no longer has to begin with a startup, a development team, or even an app idea.' },
  { type: 'p', text: 'It can begin with something much more human:' },
  { type: 'strong', text: "This doesn't work very well." },
  { type: 'strong', text: 'This takes too long.' },
  { type: 'strong', text: 'I keep forgetting this.' },
  { type: 'strong', text: 'My family struggles with this.' },
  { type: 'strong', text: 'There has to be an easier way.' },
  { type: 'p', text: "That's where ManifestOS begins." },
  { type: 'p', text: 'Not:' },
  { type: 'quote', text: 'What app do you want to build?' },
  { type: 'p', text: 'But:' },
  { type: 'strong', text: 'What problem do you wish software could solve?' },
  { type: 'p', text: "You don't need to know what kind of application you need." },
  { type: 'p', text: "You don't need to understand databases, APIs, architecture, hosting, or code." },
  { type: 'p', text: "You shouldn't have to." },
  { type: 'p', text: 'You understand the problem.' },
  { type: 'p', text: "That's enough to begin." },
  { type: 'rule' },
  { type: 'h2', text: "Human intelligence has always been distributed. The ability to build software wasn't." },
  { type: 'p', text: 'We used to think about expertise too narrowly.' },
  { type: 'p', text: 'The engineer knew technology.' },
  { type: 'p', text: 'The doctor knew medicine.' },
  { type: 'p', text: 'The teacher knew education.' },
  { type: 'p', text: 'The mechanic knew machines.' },
  { type: 'p', text: 'And everyone else was a consumer.' },
  { type: 'p', text: 'Reality is much messier and much more interesting.' },
  { type: 'p', text: "A parent can become the world's leading expert on one very specific problem affecting their child." },
  { type: 'p', text: 'A caregiver learns things about daily life that no product manager sitting in an office would ever think to ask.' },
  { type: 'p', text: 'A fisherman knows how weather, tides, wind, one particular boat ramp, and thirty years of experience interact.' },
  { type: 'p', text: 'A nurse notices problems that engineers never see.' },
  { type: 'p', text: 'A child notices things adults have learned to ignore.' },
  { type: 'p', text: 'Every person carries knowledge created by a life nobody else has lived exactly the same way.' },
  { type: 'p', text: "Until recently, most of those people couldn't turn that knowledge into software." },
  { type: 'p', text: 'Now they can.' },
  { type: 'p', text: 'We believe that matters.' },
  { type: 'rule' },
  { type: 'h2', text: 'ManifestOS exists to turn human perspective into working solutions.' },
  { type: 'p', text: 'Bring us the problem.' },
  { type: 'p', text: 'ManifestOS helps understand it.' },
  { type: 'p', text: 'It asks questions when the answers matter.' },
  { type: 'p', text: 'It looks for solutions other people have already created.' },
  { type: 'p', text: 'It proposes possibilities you may not have considered.' },
  { type: 'p', text: "And when software is the right answer, it doesn't immediately vomit out code and hope for the best." },
  { type: 'p', text: 'It thinks first.' },
  { type: 'p', text: 'It creates the blueprint.' },
  { type: 'p', text: 'It works through the user experience, features, information, architecture, risks, edge cases, tests, and implementation plan.' },
  { type: 'p', text: 'Then it builds.' },
  { type: 'p', text: 'Professional software discipline should not require the person with the idea to become a software professional.' },
  { type: 'p', text: 'The complexity belongs to the system.' },
  { type: 'p', text: 'The possibility belongs to everyone.' },
  { type: 'rule' },
  { type: 'h2', text: 'Sometimes the best software only needs one user.' },
  { type: 'p', text: 'This may be the part we care about most.' },
  { type: 'p', text: 'Not every application needs to become a startup.' },
  { type: 'p', text: 'Not every problem needs a TAM.' },
  { type: 'p', text: 'Not everything useful needs a subscription business attached to it.' },
  { type: 'p', text: 'Maybe twelve people need your solution.' },
  { type: 'p', text: 'Maybe three.' },
  { type: 'p', text: 'Maybe only you.' },
  { type: 'p', text: 'If the cost of creation becomes small enough, one person can be a sufficient market for useful software.' },
  { type: 'p', text: 'That changes what deserves to exist.' },
  { type: 'p', text: 'And occasionally, something built for one person will turn out to help thousands.' },
  { type: 'p', text: "That's fine too." },
  { type: 'p', text: 'But commercialization should be something that happens because a useful solution discovered broader demand.' },
  { type: 'p', text: "It shouldn't be the price of admission for creating the solution in the first place." },
  { type: 'rule' },
  { type: 'h2', text: "We don't want a world of isolated AI-generated apps." },
  { type: 'p', text: 'We want a world of shared problems and evolving solutions.' },
  { type: 'p', text: "If someone describes a problem you've already encountered, ManifestOS should be able to say:" },
  { type: 'strong', text: 'Someone else has dealt with something like this.' },
  { type: 'p', text: 'Maybe you can use their solution.' },
  { type: 'p', text: 'Maybe you can adapt it.' },
  { type: 'p', text: 'Maybe your situation is different enough that something new should exist.' },
  { type: 'p', text: 'Public solutions can become starting points instead of dead ends.' },
  { type: 'p', text: 'Not:' },
  { type: 'quote', text: 'Fork this repository.' },
  { type: 'p', text: 'But:' },
  { type: 'strong', text: 'Make this work for my situation.' },
  { type: 'p', text: "One teacher's solution could evolve into hundreds of variations for different classrooms." },
  { type: 'p', text: "One caregiver's tool could become useful to families she will never meet." },
  { type: 'p', text: "One mechanic's tiny utility could preserve knowledge that otherwise disappears when he retires." },
  { type: 'p', text: 'Over time, we imagine an expanding commons of human problems and the solutions people created for them.' },
  { type: 'p', text: "Software passed from person to person not because everybody wants the same thing, but because somebody else recognizes a piece of their own life in it." },
  { type: 'rule' },
  { type: 'h2', text: 'The basic ability to solve a problem should be free.' },
  { type: 'p', text: 'ManifestOS is being built around a simple commitment:' },
  { type: 'strong', text: 'You should be able to describe a problem, create an ordinary solution, use it, and share it without having to prove its economic value first.' },
  { type: 'p', text: 'If something you create begins helping a larger audience and you want help promoting it, distributing it, or turning it into a business, there can be paid services for that.' },
  { type: 'p', text: 'We are comfortable making money helping useful things travel farther.' },
  { type: 'p', text: 'We are much less interested in charging admission to the act of creating them.' },
  { type: 'p', text: 'Our incentives should be aligned with yours.' },
  { type: 'p', text: 'First:' },
  { type: 'strong', text: 'Solve something.' },
  { type: 'p', text: 'Then worry about what comes next.' },
  { type: 'rule' },
  { type: 'h2', text: 'We want to measure problems solved, not software produced.' },
  { type: 'p', text: 'The world does not need another leaderboard for how much content AI can generate.' },
  { type: 'p', text: 'More code is not the goal.' },
  { type: 'p', text: 'More apps are not the goal.' },
  { type: 'strong', text: 'More useful things becoming possible is the goal.' },
  { type: 'p', text: 'We would rather celebrate:' },
  { type: 'quote', text: "18,000 people adapted Maria's solution." },
  { type: 'p', text: 'than:' },
  { type: 'quote', text: 'Maria generated 73 applications.' },
  { type: 'p', text: 'We would rather ask:' },
  { type: 'quote', text: "Did this make someone's day easier?" },
  { type: 'p', text: 'than:' },
  { type: 'quote', text: 'How many tokens did the model produce?' },
  { type: 'p', text: 'Technology should disappear into usefulness.' },
  { type: 'rule' },
  { type: 'h2', text: 'This is the future we want to help build.' },
  { type: 'p', text: 'A world where software is not something handed down from a relatively small group of people who know how to create it.' },
  { type: 'p', text: 'A world where someone notices a problem Tuesday morning and has a useful solution by Tuesday afternoon.' },
  { type: 'p', text: "A world where good ideas don't die because they are too small." },
  { type: 'p', text: 'Where expertise hidden inside ordinary lives can become tools.' },
  { type: 'p', text: 'Where a teacher, mechanic, parent, retiree, student, caregiver, small-business owner, or twelve-year-old can turn:' },
  { type: 'strong', text: '“Someone should really make something for this.”' },
  { type: 'p', text: 'into:' },
  { type: 'strong', text: '“It exists.”' },
  { type: 'p', text: 'Not every solution will matter to everyone.' },
  { type: 'p', text: "That's the point." },
  { type: 'p', text: "The future of software doesn't have to be a handful of applications trying to serve billions of people." },
  { type: 'p', text: 'It can also be billions of small solutions, shaped by the billions of different ways people experience the world.' },
  { type: 'p', text: 'We believe a world where more people can solve problems is a better world.' },
  { type: 'p', text: 'So bring us one.' },
  { type: 'h3', text: 'ManifestOS' },
  { type: 'h3', text: "Don't bring us an app idea." },
  { type: 'h3', text: 'Bring us a problem.' },
  { type: 'strong', text: "Let's manifest the solution." },
];
